language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t hellomattelliott/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hellomattelliott/docker-react npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-481803937619"
  bucket_path: "docker-react"
  on:
    branch: master
