language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t hellomattelliott/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hellomattelliott/docker-react npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "docker-react"
  env: "DockerReact-env-1"
  bucket_name: "elasticbeanstalk-ap-southeast-2-618756747842"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
